### ISSUE TITLE
device plugin allocate judge error

### ISSUE THREAD

**Issue by angao** [AliyunContainerService/gpushare-device-plugin#1]
```go 
github.com/AliyunContainerService/gpushare-device-plugin/pkg/gpu/nvidia/allocate.go:79

// podReqGPU = uint(0)
for _, req := range reqs.ContainerRequests {
	podReqGPU += uint(len(req.DevicesIDs))
}
...
if getGPUMemoryFromPodResource(pod) == podReqGPU {
...
}
```
` getGPUMemoryFromPodResource()` returns pod memory usage, but `podReqGPU` is pod request gpu count

**Comment by angao** [comment]
@cheyang

**Comment by cheyang** [comment]
`podReqGPU` is the pod's GPU memory,  is `aliyun.com/gpu-mem`. It's because the `DevicesIDs` here is not the real GPU device ID, it's the fake DeviceIDs and the total number of the DeviceID equals GPU memory.

Maybe reading the design doc is helpful to you.  https://github.com/AliyunContainerService/gpushare-scheduler-extender/blob/master/docs/designs/designs.md#design

**Comment by angao** [comment]
thx
